<?php

return [
    'names' => [
        'EC' => 'Ecuador',
        'CL' => 'Chile',
        'PE' => 'Peru',
        'MX' => 'Mexico',
        'LAB' => 'Laboratorio',
    ],
    'currency' => [
        'EC' => '$',
        'CL' => '$',
        'PE' => 'S/.',
        'MX' => '$',
        'LAB' => '$',
    ],
    'autos_home' => [
        'locations' => [
            'EC' => ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta', 'Santo Domingo', 'Portoviejo', 'Machala', 'Loja', 'Ibarra', 'Riobamba', 'Esmeraldas'],
            'PE' => ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Cusco', 'Huancayo', 'Iquitos', 'Tacna', 'Juliaca', 'Chimbote', 'Pucallpa'],
            'CL' => ['Santiago', 'Valparaiso', 'Vina del Mar', 'Concepcion', 'La Serena', 'Antofagasta', 'Temuco', 'Rancagua', 'Talca', 'Arica', 'Iquique', 'Puerto Montt'],
            'MX' => ['Ciudad de Mexico', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Leon', 'Merida', 'Queretaro', 'Cancun', 'Toluca', 'Chihuahua', 'Aguascalientes'],
            'LAB' => ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta', 'Santo Domingo', 'Portoviejo', 'Machala', 'Loja', 'Ibarra', 'Riobamba', 'Esmeraldas'],
        ],
        'recent_searches' => [
            'EC' => [
                'Toyota Corolla en Quito',
                'Chevrolet Aveo en Guayaquil',
                'Honda Civic en Cuenca',
                'Ford Ranger en Quito',
                'Mazda 3 en Guayaquil',
                'Toyota RAV4 en Quito',
                'Nissan Sentra en Quito',
                'Hyundai Tucson en Cuenca',
                'Chevrolet Spark en Guayaquil',
            ],
            'PE' => [
                'Toyota Corolla en Lima',
                'Kia Rio en Arequipa',
                'Hyundai Accent en Trujillo',
                'Nissan Sentra en Lima',
                'Toyota Yaris en Chiclayo',
                'Suzuki Swift en Piura',
                'Mazda 3 en Cusco',
                'Chevrolet Onix en Huancayo',
                'Volkswagen Polo en Iquitos',
            ],
            'CL' => [
                'Toyota Corolla en Santiago',
                'Chevrolet Sail en Valparaiso',
                'Kia Morning en Vina del Mar',
                'Nissan Versa en Concepcion',
                'Mazda 3 en La Serena',
                'Hyundai Accent en Antofagasta',
                'Suzuki Baleno en Temuco',
                'Peugeot 208 en Rancagua',
                'Volkswagen Gol en Talca',
            ],
            'MX' => [
                'Nissan Versa en Ciudad de Mexico',
                'Chevrolet Aveo en Guadalajara',
                'Volkswagen Jetta en Monterrey',
                'Nissan Sentra en Puebla',
                'Kia Rio en Tijuana',
                'Mazda 3 en Leon',
                'Toyota Yaris en Merida',
                'Honda City en Queretaro',
                'Hyundai Grand i10 en Cancun',
            ],
            'LAB' => [
                'Toyota Corolla en Quito',
                'Chevrolet Aveo en Guayaquil',
                'Honda Civic en Cuenca',
                'Ford Ranger en Quito',
                'Mazda 3 en Guayaquil',
                'Toyota RAV4 en Quito',
                'Nissan Sentra en Quito',
                'Hyundai Tucson en Cuenca',
                'Chevrolet Spark en Guayaquil',
            ],
        ],
    ],
    'houses_home' => [
        'locations' => [
            'EC' => ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta', 'Santo Domingo', 'Portoviejo', 'Machala', 'Loja', 'Ibarra', 'Riobamba', 'Esmeraldas'],
            'PE' => ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Cusco', 'Huancayo', 'Iquitos', 'Tacna', 'Juliaca', 'Chimbote', 'Pucallpa'],
            'CL' => ['Santiago', 'Valparaiso', 'Vina del Mar', 'Concepcion', 'La Serena', 'Antofagasta', 'Temuco', 'Rancagua', 'Talca', 'Arica', 'Iquique', 'Puerto Montt'],
            'MX' => ['Ciudad de Mexico', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Leon', 'Merida', 'Queretaro', 'Cancun', 'Toluca', 'Chihuahua', 'Aguascalientes'],
            'LAB' => ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta', 'Santo Domingo', 'Portoviejo', 'Machala', 'Loja', 'Ibarra', 'Riobamba', 'Esmeraldas'],
        ],
        'popular_searches' => [
            'EC' => [
                ['label' => 'Casas en Quito', 'slug' => 'casa-quito'],
                ['label' => 'Departamentos en Guayaquil', 'slug' => 'departamento-guayaquil'],
                ['label' => 'Villas en Cuenca', 'slug' => 'villa-cuenca'],
                ['label' => 'Casas en Manta', 'slug' => 'casa-manta'],
                ['label' => 'Departamentos en Ambato', 'slug' => 'departamento-ambato'],
                ['label' => 'Terrenos en Santo Domingo', 'slug' => 'terreno-santo-domingo'],
            ],
            'PE' => [
                ['label' => 'Casas en Lima', 'slug' => 'casa-lima'],
                ['label' => 'Departamentos en Arequipa', 'slug' => 'departamento-arequipa'],
                ['label' => 'Villas en Trujillo', 'slug' => 'villa-trujillo'],
                ['label' => 'Casas en Piura', 'slug' => 'casa-piura'],
                ['label' => 'Departamentos en Cusco', 'slug' => 'departamento-cusco'],
                ['label' => 'Terrenos en Chiclayo', 'slug' => 'terreno-chiclayo'],
            ],
            'CL' => [
                ['label' => 'Casas en Santiago', 'slug' => 'casa-santiago'],
                ['label' => 'Departamentos en Valparaiso', 'slug' => 'departamento-valparaiso'],
                ['label' => 'Villas en Vina del Mar', 'slug' => 'villa-vina-del-mar'],
                ['label' => 'Casas en Concepcion', 'slug' => 'casa-concepcion'],
                ['label' => 'Departamentos en La Serena', 'slug' => 'departamento-la-serena'],
                ['label' => 'Terrenos en Antofagasta', 'slug' => 'terreno-antofagasta'],
            ],
            'MX' => [
                ['label' => 'Casas en Ciudad de Mexico', 'slug' => 'casa-ciudad-de-mexico'],
                ['label' => 'Departamentos en Guadalajara', 'slug' => 'departamento-guadalajara'],
                ['label' => 'Villas en Monterrey', 'slug' => 'villa-monterrey'],
                ['label' => 'Casas en Puebla', 'slug' => 'casa-puebla'],
                ['label' => 'Departamentos en Tijuana', 'slug' => 'departamento-tijuana'],
                ['label' => 'Terrenos en Merida', 'slug' => 'terreno-merida'],
            ],
            'LAB' => [
                ['label' => 'Casas en Quito', 'slug' => 'casa-quito'],
                ['label' => 'Departamentos en Guayaquil', 'slug' => 'departamento-guayaquil'],
                ['label' => 'Villas en Cuenca', 'slug' => 'villa-cuenca'],
                ['label' => 'Casas en Manta', 'slug' => 'casa-manta'],
                ['label' => 'Departamentos en Ambato', 'slug' => 'departamento-ambato'],
                ['label' => 'Terrenos en Santo Domingo', 'slug' => 'terreno-santo-domingo'],
            ],
        ],
    ],
];
